language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
script:
  - RAILS_ENV=test bundle exec rake --trace test
before_script:
  - cp config/database.yml.sample config/database.yml
notifications:
  recipients:
    - okkez000@gmail.com

